---
title: "Lindsay Dusard"
---

I am a Ph.D. candidate in Quantitative Methods at the University of Pennsylvania Graduate School of Education. I will also obtain an A.M. in Statistics and Data Science from the Wharton School.

My research primarily focuses on resettled refugees and other humanitarian immigrants’ access to the safety net and how that access —or lack thereof —shapes their trajectories in the U.S. education system and workforce. This work is informed by over 10 years of experience working with newcomer students and their families. My dissertation centers on a mixed-method study exploring newcomer students’ receipt of federal and state financial aid, participation in safety net programs, and their postsecondary outcomes in Virginia using novel data.

I am also interested in advancing quantitative approaches that help us better understand mechanisms and outcomes in social policy research. Recently, I have focused on text analysis, the integration of Community-Based Participatory Research (CBPR) methods in randomized controlled trials, and Bayesian Interpretation of Estimates (BASIE).

As a pre-doctoral fellow with the Institute of Education Sciences, I have completed yearlong research placements with the Urban Institute’s Immigration Cross-Center Initiative and the International Rescue Committee.

```{r}
1 + 1
```
