---
title: ""
---

## Peer-reviewed Research

#### [**Integrating Community-Based Participatory Research Methods in Randomized Controlled Trials: An Interdisciplinary Systematic Review**](https://doi.org/10.5840/inquiryct20254919)

Lindsay Dusard and [Wendy Castillo](https://www.montclair.edu/profilepages/view_profile.php?username=castillow). 2025. *Inquiry:* *Critical Thinking Across Disciplines*

-   *Paper presented at [SREE 2024](https://sree.confex.com/sree/2024/meetingapp.cgi/Paper/5695) and [APPAM 2024](https://appam.confex.com/appam/2024/meetingapp.cgi/Paper/55169)*

## Works in Progress

#### **Associations of caregiver investments and early childhood outcomes in refugee and host households in Uganda**

Lindsay Dusard, [Sarah Kabay](https://poverty-action.org/people/sarah-kabay), [Dana McCoy](https://www.gse.harvard.edu/directory/faculty/dana-mccoy), and [Sharon Wolf](https://www.gse.upenn.edu/faculty/sharon-wolf)

-   *Paper presented at [SRCD 2025](https://srcd.secure-platform.com/site/solicitations/102002/sessiongallery/schedule/items/94172)*

#### **Newcomer Students Enrolled in Higher Education in Virginia: An Analysis of Financial Aid Access and Safety Net Participation**

Lindsay Dusard

-   *Paper to be presented at [APPAM 2025](https://convention2.allacademic.com/one/appam/appam25/index.php?cmd=Online+Program+View+Session&selected_session_id=2260282&PHPSESSID=1r6hdr7rrkprclpo44dqesj7ao)*

#### **Assessing Changes in Teacher Reflections Using Sentiment-Based Textual Analysis**

[Wendy Chan](https://www.gse.upenn.edu/faculty/wendy-chan), Xinhe (Lindsey) Lui, Lindsay Dusard, Chen Li, Mingjun Yang, Grace Barry, Abby Reisman, Timothy Patterson, Joseph Eisman, Avi Kaplan

-   *Paper pesented at [AERA 2025](https://convention2.allacademic.com/one/aera/aera25/index.php?cmd=Online+Program+View+Paper&selected_paper_id=2186570&PHPSESSID=07u0jogkdjf14pb6ulb6q1ctl2), poster to be presented at [SREE 2025](https://builder.guidebook.com/g/#/guides/sree2025/schedule/sessions/31565871)*

#### **Prior Selection in Bayesian Impact Analysis: A Simulation Study**

Lindsay Dusard

-   *Paper to be presented at [APPAM 2025](https://convention2.allacademic.com/one/appam/appam25/index.php?cmd=Online+Program+View+Paper&selected_paper_id=2260845&PHPSESSID=1r6hdr7rrkprclpo44dqesj7ao)*

#### **Realities of researching together: Navigating tensions in community-based participatory research in causal studies**

[Wendy Castillo](https://www.montclair.edu/profilepages/view_profile.php?username=castillow) and Lindsay Dusard

#### **Refugee children’s receipt of and factors that impact their receipt of special education services in Virginia**

[Nicole Adams](https://spcd.charlotte.edu/people/nicole-adams/) and Lindsay Dusard
