---
title: ""
---

## Technical Assistance

#### [**What You Should Know About the Free Application for Federal Student Aid (FAFSA) Updates**](https://www.switchboardta.org/blog/what-you-should-know-about-the-free-application-for-federal-student-aid-fafsa-updates-2/)

Blog for Switchboard (2023).

#### [**Accessing Federal Student Aid for Newcomers: The Latest Guidance from the U.S. Department of Education**](https://www.switchboardta.org/resource/accessing-federal-student-aid-for-newcomer-youth-and-adults-the-latest-guidance-from-the-u-s-department-of-education/)

Webinar for Switchboard (2023).

#### [**Accessing Federal Student Aid for Refugee Youth and Adults: Resources and Tips for Successful Application Processing**](https://www.switchboardta.org/resource/accessing-federal-student-aid-for-refugee-youth-and-adults-resources-and-tips-for-successful-application-processing/) 

Toolkit for Switchboard(2023).

#### [**Can Afghan Newcomers Access Title IV, Federal Student Aid? Answering FAQ’s About New Guidance from the U.S. Department of Education**](https://www.switchboardta.org/blog/elementor-21878/) 

Blog for Switchboard(2022).

#### [**The Golden Ticket: Accessing Financial Aid for Refugee Youth and Adults’**](https://www.switchboardta.org/resource/the-golden-ticket-accessing-financial-aid-for-refugee-youth-and-adults/) 

Webinar for Switchboard(2021).

## Blog

#### [**The Travel Ban Doesn’t Just Keep People Out. It Also Hurts Families Who Are Already Here**](https://www.urban.org/urban-wire/travel-ban-doesnt-just-keep-people-out-it-also-hurts-families-who-are-already-here)

with [Diana Guelespe](https://www.urban.org/author/diana-guelespe). Blog for the Urban Institute (2025).
